#ifndef ALLEGRO_CONSTANTS_H
#define ALLEGRO_CONSTANTS_H

#define ALLEGRO_FONT_C "assets/fonts/upheavtt.ttf"

#define SCREEN_WIDTH 360
#define SCREEN_HEIGHT 640

#define BLOCK_SIZE 20

#define FIELD_WIDTH (SCREEN_WIDTH / BLOCK_SIZE)
#define FIELD_HEIGHT (SCREEN_HEIGHT / BLOCK_SIZE)

#define TESTING_DELAY 5

#endif